/**
 * Supported languages for Satim API
 */
export type SatimLanguage = 'fr' | 'en' | 'ar';

/**
 * HTTP method for API requests
 */
export type HttpMethod = 'POST' | 'GET';

/**
 * Logger interface for the SDK
 */
export interface SatimLogger {
  debug(obj: Record<string, unknown>, msg?: string): void;
  info(obj: Record<string, unknown>, msg?: string): void;
  warn(obj: Record<string, unknown>, msg?: string): void;
  error(obj: Record<string, unknown>, msg?: string): void;
}

/**
 * Log level for the SDK
 */
export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

/**
 * HTTP configuration options
 */
export interface HttpConfig {
  /** HTTP method to use (default: POST) */
  method?: HttpMethod;
  /** Request timeout in milliseconds (default: 30000) */
  timeoutMs?: number;
  /** Connection timeout in milliseconds (default: 10000) - best effort */
  connectTimeoutMs?: number;
  /** Verify SSL certificates (default: true) */
  verifySSL?: boolean;
}

/**
 * Logger configuration options
 */
export interface LoggerConfig {
  /** Enable development logging (default: true if NODE_ENV !== 'production') */
  enableDevLogging?: boolean;
  /** Log level (default: 'info') */
  level?: LogLevel;
}

/**
 * Satim client configuration
 */
export interface SatimConfig {
  /** Merchant's login received during registration */
  userName: string;
  /** Merchant's password received during registration */
  password: string;
  /** Terminal ID assigned by bank to Merchant */
  terminalId: string;
  /** API base URL */
  apiBaseUrl: string;
  /** Default language (default: 'fr') */
  language?: SatimLanguage;
  /** Currency code according to ISO 4217 (default: '012' for DZD) */
  currency?: string;
  /** HTTP configuration */
  http?: HttpConfig;
  /** Logger configuration */
  logger?: LoggerConfig;
}

/**
 * JSON parameters for register request
 */
export interface RegisterJsonParams {
  /** Terminal ID (required) */
  force_terminal_id: string;
  /** User defined field 1 - required */
  udf1: string;
  /** User defined field 2 - optional */
  udf2?: string;
  /** User defined field 3 - optional */
  udf3?: string;
  /** User defined field 4 - optional */
  udf4?: string;
  /** User defined field 5 - optional */
  udf5?: string;
  /** Payment Transaction Type Indicator (e.g., 'CP' or '698' for bill payment) */
  fundingTypeIndicator?: string;
}

/**
 * Parameters for registering an order
 */
export interface RegisterOrderParams {
  /** Order number in the merchant's system - must be unique per transaction */
  orderNumber: string;
  /** Amount in DZD (minimum 50 DZD) - will be converted to minor units */
  amount: number | string;
  /** URL to redirect after successful payment */
  returnUrl: string;
  /** URL to redirect if payment failed */
  failUrl?: string;
  /** Free-form description of the order */
  description?: string;
  /** Language override (uses config default if not specified) */
  language?: SatimLanguage;
  /** Currency override (uses config default if not specified) */
  currency?: string;
  /** User defined field 1 - required */
  udf1: string;
  /** User defined field 2 - optional */
  udf2?: string;
  /** User defined field 3 - optional */
  udf3?: string;
  /** User defined field 4 - optional */
  udf4?: string;
  /** User defined field 5 - optional */
  udf5?: string;
  /** Payment Transaction Type Indicator */
  fundingTypeIndicator?: string;
}

/**
 * Raw response from register.do endpoint
 */
export interface RegisterOrderRawResponse {
  /** Error code (0 for success) */
  errorCode?: number | string;
  /** Unique order ID generated by EPG */
  orderId?: string;
  /** URL of the payment page for customer redirect */
  formUrl?: string;
  /** Error message if registration failed */
  errorMessage?: string;
}

/**
 * Normalized response from register.do endpoint
 */
export interface RegisterOrderResponse {
  /** Raw response from API */
  raw: RegisterOrderRawResponse;
  /** Normalized error code as number */
  errorCode: number;
  /** Unique order ID generated by EPG */
  orderId: string | null;
  /** URL of the payment page for customer redirect */
  formUrl: string | null;
  /** Check if registration was successful */
  isSuccessful(): boolean;
}

/**
 * Raw response from acknowledgeTransaction.do endpoint
 */
export interface ConfirmOrderRawResponse {
  /** Card expiration date (YYYYMM format) */
  expiration?: string;
  /** Name of the cardholder */
  cardholderName?: string;
  /** Amount to be debited in order currency */
  depositAmount?: number;
  /** Currency code */
  currency?: string;
  /** Authorization response ID */
  authorizationResponseId?: string;
  /** IPS authorization code */
  approvalCode?: string;
  /** Processing system authorization code */
  actionCode?: number | string;
  /** Action code description */
  actionCodeDescription?: string;
  /** Error code */
  ErrorCode?: number | string;
  /** Error message */
  ErrorMessage?: string;
  /** Order status */
  OrderStatus?: number | string;
  /** Order number in merchant's system */
  OrderNumber?: string;
  /** Masked card number */
  Pan?: string;
  /** Amount in minor units */
  Amount?: number | string;
  /** Customer IP address */
  Ip?: string;
  /** Customer ID in merchant system */
  clientId?: string;
  /** Binding ID */
  bindingId?: string;
  /** Payment account reference */
  paymentAccountReference?: string;
  /** Order description */
  Description?: string;
  /** Additional parameters */
  params?: Record<string, unknown>;
  /** SVFE response code */
  SvfeResponse?: string;
  /** Allow additional unknown fields */
  [key: string]: unknown;
}

/**
 * Normalized response from acknowledgeTransaction.do endpoint
 */
export interface ConfirmOrderResponse {
  /** Raw response from API */
  raw: ConfirmOrderRawResponse;
  /** Normalized error code as number */
  errorCode: number;
  /** Normalized order status as number */
  orderStatus: number | null;
  /** Normalized amount as number */
  amount: number | null;
  /** Order number */
  orderNumber: string | null;
  /** Masked card number */
  pan: string | null;
  /** Action code description */
  actionCodeDescription: string | null;
  /** Check if confirmation was successful */
  isSuccessful(): boolean;
  /** Check if order was paid (status 2) */
  isPaid(): boolean;
}

/**
 * Raw response from refund.do endpoint
 */
export interface RefundOrderRawResponse {
  /** Error code (0 for success) */
  errorCode?: number | string;
  /** Error message */
  errorMessage?: string;
}

/**
 * Normalized response from refund.do endpoint
 */
export interface RefundOrderResponse {
  /** Raw response from API */
  raw: RefundOrderRawResponse;
  /** Normalized error code as number */
  errorCode: number;
  /** Error message if any */
  errorMessage: string | null;
  /** Check if refund was successful */
  isSuccessful(): boolean;
}

/**
 * Order status codes from Satim
 */
export const OrderStatus = {
  REGISTERED_NOT_PAID: 0,
  UNKNOWN_DECLINE: -1,
  APPROVED: 1,
  DEPOSITED: 2,
  REVERSED: 3,
  REFUNDED: 4,
  DECLINED: 6,
  CARD_ADDED: 7,
  CARD_UPDATED: 8,
  CARD_VERIFIED: 9,
  RECURRING_ADDED: 10,
  DEBITED: 11,
} as const;

export type OrderStatusCode = (typeof OrderStatus)[keyof typeof OrderStatus];
